### ISSUE TITLE
Android HTTP 500 Crashes App

### ISSUE THREAD

**Issue by mwcaisse** [mwcaisse/AndroidFT#30]
If the servlet returns a 500 ISE when the android app makes a request. The exception is not caught anywhere and bubbles up causing the whole application to crash.

Example stack trace below:

09-16 21:05:08.792: W/RestTemplate(21994): POST request for "http://192.168.1.160:8080/aft-servlet/manager/device/register" resulted in 500 (Internal Server Error); invoking error handler
09-16 21:05:08.792: W/dalvikvm(21994): threadid=14: thread exiting with uncaught exception (group=0x4167cce0)
09-16 21:05:08.802: E/AndroidRuntime(21994): FATAL EXCEPTION: AsyncTask #3
09-16 21:05:08.802: E/AndroidRuntime(21994): Process: com.ricex.aft.android, PID: 21994
09-16 21:05:08.802: E/AndroidRuntime(21994): java.lang.RuntimeException: An error occured while executing doInBackground()
09-16 21:05:08.802: E/AndroidRuntime(21994):    at android.os.AsyncTask$3.done(AsyncTask.java:300)
09-16 21:05:08.802: E/AndroidRuntime(21994):    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
09-16 21:05:08.802: E/AndroidRuntime(21994):    at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
09-16 21:05:08.802: E/AndroidRuntime(21994):    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
09-16 21:05:08.802: E/AndroidRuntime(21994):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
09-16 21:05:08.802: E/AndroidRuntime(21994):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
09-16 21:05:08.802: E/AndroidRuntime(21994):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
09-16 21:05:08.802: E/AndroidRuntime(21994):    at java.lang.Thread.run(Thread.java:841)
09-16 21:05:08.802: E/AndroidRuntime(21994): Caused by: org.springframework.web.client.HttpServerErrorException: 500 Internal Server Error
09-16 21:05:08.802: E/AndroidRuntime(21994):    at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:78)
09-16 21:05:08.802: E/AndroidRuntime(21994):    at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:524)
09-16 21:05:08.802: E/AndroidRuntime(21994):    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:481)
09-16 21:05:08.802: E/AndroidRuntime(21994):    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:439)
09-16 21:05:08.802: E/AndroidRuntime(21994):    at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:317)
09-16 21:05:08.802: E/AndroidRuntime(21994):    at com.ricex.aft.android.requester.DeviceRequester.registerDevice(DeviceRequester.java:37)
09-16 21:05:08.802: E/AndroidRuntime(21994):    at com.ricex.aft.android.gcm.GCMRegister$2.doInBackground(GCMRegister.java:194)
09-16 21:05:08.802: E/AndroidRuntime(21994):    at com.ricex.aft.android.gcm.GCMRegister$2.doInBackground(GCMRegister.java:1)
09-16 21:05:08.802: E/AndroidRuntime(21994):    at android.os.AsyncTask$2.call(AsyncTask.java:288)
09-16 21:05:08.802: E/AndroidRuntime(21994):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-16 21:05:08.802: E/AndroidRuntime(21994):    ... 4 more
09-16 21:05:08.812: W/ActivityManager(626):   Force finishing activity com.ricex.aft.android/.PushFile
09-16 21:05:09.072: W/HandlerScheduledExecuto(1691): Task does not implement UiTask. Consider using NamedUiRunnable for eww@4234ce68

**Comment by mwcaisse** [comment]
Related to Issue #44
